feat(bmks): add select browser for selected bookmark

diff --git a/bmks b/bmks
--- a/bmks
+++ b/bmks
@@ -1,37 +1,44 @@
 #!/bin/bash
 # bmks: unix bookmark management tool
 #
-# It takes an argument and an url, it can add, delete, list, and open through
+# It takes an argument and a URL, it can add, delete, list, and open through
 # dmenu the list of bookmarks with a browser of choice.
 #
 
 URL_FILE_PATH=$HOME/.bmks/
 URL_FILE_NAME=urls
-
 DMENU_WIDTH=1366
 DMENU_NUMBER_LINES=20
-
-show_usage() {
-	printf "bmks: unix bookmark management that sucks less
-
-usage:
-bmks dmenu
-	manual switch for displaying bookmarks in dmenu
-
-Dmenu will display a menu that will allow you to choose a bookmark and open it in your default browser."
-}
+DMENU_BROWSER_WIDTH=360
+BROWSERS=(
+	"firefox"
+	"firefox-developer-edition"
+	"google-chrome-stable"
+	"google-chrome-unstable"
+	"qutebrowser"
+)
 
 bmks_display() {
 	bmks_check
-    grep -v '^#' "$URL_FILE_PATH/$URL_FILE_NAME" | sort |
+		selected_url=$(grep -v '^#' "$URL_FILE_PATH/$URL_FILE_NAME" | sort |
 		dmenu -l $DMENU_NUMBER_LINES -z $DMENU_WIDTH |
-		awk -F ' - ' '{print $4}' |
-		xargs -I '{}' "$BROWSER" {}
+		awk -F ' - ' '{print $4}')
+		[ -z "$selected_url" ] && exit 0
+
+		selected_browser=$(printf "%s\n" "${BROWSERS[@]}" | dmenu -l ${#BROWSERS[@]} -z $DMENU_BROWSER_WIDTH)
+		[ -z "$selected_browser" ] && exit 0
+
+		case "$selected_browser" in
+				"firefox" | "firefox-developer-edition" | "google-chrome-stable" | "google-chrome-unstable" | "qutebrowser")
+						"$selected_browser" "$selected_url" ;;
+				*)
+						printf "Error: Unsupported browser selected.\n" && exit 1 ;;
+		esac
 }
 
 bmks_check() {
 	[ ! -s "$URL_FILE_PATH/$URL_FILE_NAME" ] &&
-		printf "Error: No bookmarks found to display. Try adding some!\n\n" && show_usage &&
+		printf "Error: No bookmarks found to display. \nTry adding some to %s.\n" "$URL_FILE_PATH$URL_FILE_NAME" &&
 		exit 0
 }
 
